version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    # reviewers:
    #   - "asulwer"
    
  - package-ecosystem: "nuget"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    # reviewers:
    #   - reviewer_one
